version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Port untuk AMQP (pengiriman/penerimaan pesan)
      - "15672:15672" # Port untuk RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge
